services:
  geometry-api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=development
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/geometry_api_development
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY:-}
    depends_on:
      - postgres
    volumes:
      - .:/rails
      - bundle_cache:/usr/local/bundle
    command: >
      sh -c "
        bundle install &&
        bundle exec rails db:create db:migrate &&
        bundle exec rails server -b 0.0.0.0 -p 3000
      "
    stdin_open: true
    tty: true

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=geometry_api_development
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local
  bundle_cache:
    driver: local
